### ISSUE TITLE
Dynamic group can't use IP

### ISSUE THREAD

**Issue by abeudin** [fusioninventory/fusioninventory-for-glpi#1705]
In GLPI 0.85 and Fusioninventory 0.85+1.3 is impossible to make dynamic group with IP. There are all parameters but i can't find IP.

**Comment by nbriche** [comment]
Don't you mean "IP range"? I can't think of a use case for a full IP test in a dynamic group.  Either a client's IP is dynamic, in which case its exact IP is kind of irrelevant considering the address space; or its IP is static, in which case it's also kind of irrelevant, since there wouldn't be much of a difference between IP and ID to identify the client.  I could see a use case for IP range, though.

**Comment by abeudin** [comment]
Yes i mean IP range like 192.168.10.*

**Comment by nbriche** [comment]
I though rather like "IP range" as defined in FusionInventory's menus (Network/IP Range), which would give you a much finer control.

**Comment by abeudin** [comment]
is a good idea to the IP range defined in FusionInventory

**Comment by abeudin** [comment]
is possible to backport it in fusioninventory 0.85 because this functionality is available in 0.84

**Comment by ddurieux** [comment]
Sorry not really understand :/

**Comment by ddurieux** [comment]
Ok I have seen you want ;)
