### ISSUE TITLE
Improvement: update inventory if device got online

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [fusioninventory/fusioninventory-for-glpi#2669]
Hello,

current it seems that the Agent will run only every X hours like setting in configuration. A solution for "sent if online next time" would be a great improvement.

Example: Notebooks of traveling salesmen which are unfrequent online above vpn. In Result- the devices aren't update a long time.

regards

**Comment by Wolvverine** [comment]
Try GPO with taskscheduler and task on boot/connect vpn.

**Comment by vollkommenIrrelevant** [comment]
That may work. In combination with [this ](https://github.com/fusioninventory/fusioninventory-agent-windows-installer/issues/2) a better solution  is important.

**Comment by vollkommenIrrelevant** [comment]
@g-bougard 
of course. But - in fact one part of the problem is the missing reliability of the task scheduler. And, maybe, there will be a solution for both problems with param.

**Comment by g-bougard** [comment]
@vollkommenIrrelevant 

Actually, you have the `PROLOG_FREQ` parameter which will ask the agent to contact the server each `PROLOG_FREQ` hours. In a large infrastructure, you won't want this parameter to be too short.

On network error, you should see `No answer from server at ...` error message in the agent log file. In that case, and on the first error, the agent will retry 1 minutes later. If that fails again, it doubles the delay before retrying. If that fails again and again it doubles the delay until reaching the actual max delay (`PROLOG_FREQ` hours).

Your problem is then the next delay timeout occurs while a travelling notebook becomes online.

Maybe our algorithm is too simple and we may want to keep it short on network error, maybe one hour max. This could even be configured with a new parameter.

Btw this is not a [fusioninventory-for-glpi](https://github.com/fusioninventory/fusioninventory-for-glpi) but a [fusioninventory-agent](https://github.com/fusioninventory/fusioninventory-agent/issues) one.

I'm closing the issue here and please open a new one on the right place, referencing this one.

Thank you.

**Comment by vollkommenIrrelevant** [comment]
Thanks. Where did you open the new one? Maybe this could be part of Ideas for Version 3?

**Comment by g-bougard** [comment]
Sorry, but I didn't open a new one as I asked you to do so ;-)
And yes, it would be nice to add this to next 2.4.3 release.

**Comment by vollkommenIrrelevant** [comment]
oh, sorry - i misunderstood that.
