### ISSUE TITLE
Error message: GLPI cron does not run, see documentation

### ISSUE THREAD

**Issue by brisingertrece** [fusioninventory/fusioninventory-for-glpi#2883]
Hello everyone.
I have installed GLPI + Fusion inventory.
I have installed a + NetDiscovery - NetInventory agent on the same network.
Agent inventory works correctly.
The problem is that when I schedule a network discovery task, it runs after the set time interval.
The problem I am sure is something related to the error "GLPI cron does not run, see documentation".
My cron configuration:
crontab -l
* * * * * / opt / rh / rh-php71 / root / bin / php /var/www/glpi/front/cron.php &> / dev / null
crontab -l -u apache
* * * * * / opt / rh / rh-php71 / root / bin / php /var/www/glpi/front/cron.php &> / dev / null

![image](https://user-images.githubusercontent.com/56825752/67201019-9a2a7b80-f405-11e9-8101-e5423d9ae53d.png)

![image](https://user-images.githubusercontent.com/56825752/67201084-c2b27580-f405-11e9-85cc-1b4e601591cc.png)

Setup:
Centos 7
PHP 7.1.30
httpd24
GLPI 9.4.4
FusionInventory 9.4 + 1.1
Fusioninventory agent (2.5.1-1) - NetDiscovery - NetInventory (v4.0)

**Comment by erald95** [comment]
This might sound dumb but in what directory is GLPI on your computer. I'm saying this becasue in my case i had GLPI in <code>/var/www/**html**/glpi</code> and I was trying `/usr/bin/php /var/www/glpi/front/cron.php &>/dev/null` instead of <code>/usr/bin/php /var/www/**html**/glpi/front/cron.php &>/dev/null</code>.

If you already have the right directory and still doesn't work try it with `sudo`. At least for me this worked.

Hope this helps!

**Comment by brisingertrece** [comment]
It has been fixed by changing the php installation method.
I have uninstalled php7.1, and I have installed it again from another repository in version 7.4
Somehow everything seems to work normally.

**Comment by ddurieux** [comment]
Be carefull, GLPI is not compatible with PHP 7.4 (and PHP 7.4 not yet released)
