### ISSUE TITLE
[Deploy] My package keep reinstalling in spite of audit check

### ISSUE THREAD

**Issue by xeoslaenor** [fusioninventory/fusioninventory-for-glpi#3097]
Hello,

Some of my packages keep reinstalling in spite of my audit check : 

[Wed Feb 17 18:12:47 2021][info] running task Deploy
[Wed Feb 17 18:12:47 2021][debug] Free space on C:\Program Files\FusionInventory-Agent\var\https..__glpi.necs.eu_plugins_fusioninventory\deploy: 21791
[Wed Feb 17 18:12:47 2021][debug] check success: "C:\Program Files (x86)\TeamViewer\TeamViewer.exe" file is missing
[Wed Feb 17 18:12:47 2021][debug] check #1: Recherche d'une installation antérieure, got ok, skip, "C:\Program Files (x86)\TeamViewer\TeamViewer.exe" file is missing
[Wed Feb 17 18:13:05 2021][debug] ================================
[Wed Feb 17 18:13:05 2021][debug] Started cmd: "\\data1.necs.eu\SI\LOGICIELS\os_windows\3 - Silent-Installations\Base\install_teamviewer.bat"
[Wed Feb 17 18:13:05 2021][debug] ================================
[Wed Feb 17 18:13:05 2021][debug] 
[Wed Feb 17 18:13:05 2021][debug] C:\Program Files\FusionInventory-Agent\perl\bin>cd "C:\Program Files\FusionInventory-Agent\var\https..__glpi.necs.eu_plugins_fusioninventory\deploy\workdir\602d4e471908a" 
[Wed Feb 17 18:13:05 2021][debug] 
[Wed Feb 17 18:13:05 2021][debug] C:\Program Files\FusionInventory-Agent\var\https..__glpi.necs.eu_plugins_fusioninventory\deploy\workdir\602d4e471908a>"\\data1.necs.eu\SI\LOGICIELS\os_windows\3 - Silent-Installations\Base\install_teamviewer.bat"
[Wed Feb 17 18:13:05 2021][debug] --------------------------------
[Wed Feb 17 18:13:05 2021][debug] exit status: `0'
[Wed Feb 17 18:13:05 2021][debug] exit status is ok: 0
[Wed Feb 17 18:13:05 2021][debug] final status: 1

I have defined a package with an audit check : 

File does not exist
"C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
If fails, skip job

So the command should not be executed again... but it does

I suspect a problem with (x86) bad encoding as it keeps reinstalling these ones (no problem for normal Program Files)
Do you know this problem ? How can I encode my path properly ?

**Comment by eduardomozart** [comment]
This problem seems more related to the FusionInventory Agent itself than FusionInventory for GLPI. I recommend you open an issue at https://github.com/fusioninventory/fusioninventory-agent/issues
An workaround would be editing ``install_teamviewer.bat`` script itself to check if the file "C:\Program Files (x86)\TeamViewer\TeamViewer.exe" exists and, if so, the script isn't executed. I'm not a big fan of using such simple detection mechanisms, I would instead checking the HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall key and compare the TeamViewer remote installer version with the local computer TeamViewer installed version, if it doesn't exists or it's outdated than the server version, the TeamViewer install would be trigged. FusionInventory doesn't support this natively, so you would need to do this check yourself at your script.
An alternative to have FusionInventory dinamically upgrading TeamViewer would be creating a FusionInventory Dynamic Group to check if TeamViewer is installed and adding computers automatically to this group to run the TeamViewer deploy task automatically when TeamViewer was not found, similar to the example of Collect documentation - https://fusioninventory.org/documentation/tasks/collect.html -, but actually the Dynamic Group functionality that supports it is broken (#3101). so it's not possible to do that at the moment.

**Comment by xeoslaenor** [comment]
I fixed the problem. I wrote the path in GLPI plugin field with quotes like "C:\Program Files (x86)\TeamViewer\TeamViewer.exe"
I removed quotes and it works perfectly now. Quoting was surely creating problems with (x86) part. I thought adding them was a good idea to avoid any encoding problem, it was not :/

Yet, I take note of your advices, thank you

**Comment by ddurieux** [comment]
Perhaps it's because you have space in the path ?

**Comment by xeoslaenor** [comment]
Might be yes
C:\Program Files (x86)\TeamViewer\TeamViewer.exe in the field works
"C:\Program Files (x86)\TeamViewer\TeamViewer.exe" not
" " surely make the string interpreted wrongly
