### ISSUE TITLE
problem with deployment of package and path /var/www

### ISSUE THREAD

**Issue by dcantos1** [fusioninventory/fusioninventory-for-glpi#3119]
I have the problem in the latest version of the fusion inventory plugins, I can't upload my application, I don't get the option and the other error is the path when I try to open the package manager, it gives me path /var/www ..... etc . attached images

Versión Centos 7.6
Apache 2
php7,3
MariaDB 10

P:D: I am looking like crazy how to upload my .exe but I think that option for some problem does not come up = (

![Captura3](https://user-images.githubusercontent.com/80493416/110870864-50ad2b80-829b-11eb-9d78-a828b65ead69.PNG)
![Captura2](https://user-images.githubusercontent.com/80493416/110870869-51de5880-829b-11eb-99b2-d3a0bdb87d93.PNG)
![Captura1](https://user-images.githubusercontent.com/80493416/110870874-5276ef00-829b-11eb-9fd1-ffad0f5103f4.PNG)

**Comment by ddurieux** [comment]
See this patch: https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3110
Before release, we need fix many other parts because GLPI 9.5.4 is a major release because functions are modified, so we need update some parts

**Comment by dcantos1** [comment]
Thank you very much brother and a question and excuse me I am new to this and I want to deploy an application that I have but I am trying and I do not know where to upload my .MSI I have no idea can you help me please, in the cloud version of it there is a bug that I cannot create  a dynamic group does not load the page and I want to throw in the towel.

**Comment by ddurieux** [comment]
Yes, it's the problem of 9.5.4, many part of plugin is broken for the moment

**Comment by ddurieux** [comment]
What cloud version?
Not understand

**Comment by PierreTeclib** [comment]
https://www.glpi-network.cloud/home-fr.php

**Comment by ddurieux** [comment]
Ok, so see with your cloud provider, I don't know how they install the plugin

**Comment by bvessey** [comment]
It looks like it's whatever performs the url rewrite but just for the "Deploy" dropdown.  If I remove the "var/www/html" from the urls by hand it gets to the package listing.  From there we can view the list of packages and some functionalities, but other functions are missing or otherwise unavailable.  Please let me know if there's any information or assistance that I can provide.  On peut également communiquer en français si c'est plus simple.  Thanks / Merci!

-- EDIT--
Applied the patch above (#3110 ) which resolves the re-write issue.
