### ISSUE TITLE
I want to get PluginFusioninventoryNetworkPort data using the GLPI API, but access is denied

### ISSUE THREAD

**Issue by anyqov** [fusioninventory/fusioninventory-for-glpi#3203]
Hello!
I want to get PluginFusioninventoryNetworkPort data using the GLPI API, but access is denied. At the same time, all rights have been added to the Fusioninventory tab. How do I add rights to receive PluginFusioninventoryNetworkPort data using the GLPI API?

API request http://glpi_address/glpi/apirest.php/PluginFusioninventoryNetworkPort/28/:
[
    "ERROR_RIGHT_MISSING",
    "You don't have permission to perform this action."
]

![image](https://user-images.githubusercontent.com/56084389/127227984-ea30a496-63f1-441b-a3c8-f43a05df5697.png)
![image](https://user-images.githubusercontent.com/56084389/127228045-5cb37e18-7549-4d3a-8f93-af1387205494.png)

**Comment by ddurieux** [comment]
It's a bad idea to use GLPI API with FusionInventory plugin because due to bad implementation of the GLPI API (very bad design), it's impossible to use for the plugin FusionInventory.

I tried many months ago to update for it but require too many changes and modify the design of the plugin structure, and it's a really bad idea to do it (problems with security, performances...)

**Comment by anyqov** [comment]
It's a pity that I can't even get the data. Thanks for the answer.
